# Generated by Django 3.2.4 on 2021-06-27 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('image_url', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('age', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
