# Generated by Django 3.2.4 on 2021-06-22 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(130), django.core.validators.MinValueValidator(18)])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
