CREATE TABLE pet_owner (
	owner_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	owner_name VARCHAR(15),
	owner_age INT CHECK (owner_age BETWEEN 1 AND 110))

CREATE TABLE dog (
	dog_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	owner_id INT REFERENCES pet_owner(owner_id),
	dog_name VARCHAR(15),
	dog_age INT CHECK (dog_age BETWEEN 1 AND 25)
)

CREATE TABLE cat(
	cat_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	owner_id INT REFERENCES pet_owner(owner_id),
	cat_name VARCHAR(15),
	cat_age INT CHECK (cat_age BETWEEN 1 AND 25)
)

CREATE TABLE hotel(
	hotel_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	hotel_name VARCHAR(25),
	hotel_stars INT CHECK (hotel_stars BETWEEN 1 AND 5)
)

CREATE TABLE cat_room(
	room_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	cat_id INT REFERENCES cat(cat_id),
	hotel_id INT REFERENCES hotel(hotel_id),
	register_date DATE,
	unregister_date DATE
)

CREATE TABLE dog_room(
	room_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	dog_id INT REFERENCES dog(dog_id),
	hotel_id INT REFERENCES hotel(hotel_id),
	register_date DATE,
	unregister_date DATE
	)
